# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

  # netlify.toml
  [[redirects]]
    force = true
    from = '/api/*'
    status = 200
    to = '/.netlify/functions/:splat'


  # Uncomment to use this redirect for Single Page Applications like create-react-app.
  # Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
    command = "npm run dev" # Command to start your dev server
    publish = "dist" # Folder with the static content for _redirect file
    functionsPort = 8885

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
