export enum Category {
  DX = 'DX',
  Digital = 'Digital',
  'Mobile Inside Arkansas' = 'Mobile Inside Arkansas',
  'Mobile Outside Arkansas' = 'Mobile Outside Arkansas',
  'Multi Operator' = 'Multi Operator',
  'Portable Inside Arkansas' = 'Portable Inside Arkansas',
  'Portable Outside Arkansas' = 'Portable Outside Arkansas',
  Rover = 'Rover',
  'Single Operator High Power, Mixed' = 'Single Operator High Power, Mixed',
  'Single Operator Low Power, Mixed' = 'Single Operator Low Power, Mixed',
  'Single Operator QRP, Mixed' = 'Single Operator QRP, Mixed',
  'Single Operator High Power, All CW' = 'Single Operator High Power, All CW',
  'Single Operator Low Power, All CW' = 'Single Operator Low Power, All CW',
  'Single Operator High Power, All SSB' = 'Single Operator High Power, All SSB',
  'Single Operator Low Power, All SSB' = 'Single Operator Low Power, All SSB',
}
